language: ruby
rvm:
- 2.3.0
script:
- rspec
deploy:
  provider: rubygems
  api_key:
    secure: SL1Wqrqa61Es8ogFckEUsq04mrZlWET+t3XfL1YkQNMoMeTu56E21uZViK8/54+QEao2abYVEDNHzSy0Z7Q2OuLap9guCeb69oLXUwDO3sX8kaHIlRUlECXIWNTdyNNmPB+jCOWVwvZgsyI2xI7UR7VTI03vWv4jXFh27KzPZNHwPdRHI/4Ydgh+C9J7bYZeHM4K0h6vq+0MSBsIm226FbcJLchvh1kae3dzhFcIXqzdzG54dlWuiv3CiNoj+4inPEo5D/Pws8KJle/FyUGi/q1qUVuw1iv+U9ASmu/eCawotAVKrHLWDwJ66Synhr3edcVJ2O1wqJDP4TvABGWomaExQdkHEJFvhPPdLVjqvEkUSjzZariFVNag5apJ577HDjDRObdcXoAop9xodj7S30e/JIzb6LhtJWKTTi8iILEBnT4ETFX4ogZb3gahl5dlQd9TfMD/cf+Fl/Nc/RqJZG2OQN1ECwwShS3r9icTqYX4cSTm/5KJvFdX9s416OG6YnJckqfMuEFIyh/Zfz2d/OPANpgOHSH2+hA90EDQUnfu3hjUBR/Lh1y0zC9bvYvBAgj5j4i61M+91zBRzEfew/+ASdPx29VkLVLalBqMcgZY77zYJVmanmwIHCPVOO6eTAjCqm7yojXdZWXUewNhdacomH/47GLtz/sxtjFdprs=
  gem: squcumber-postgres
  on:
    tags: true
    repo: moertel/sQucumber-postgres
